/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedReportsIndexRouteImport } from './routes/_protected/reports/index'
import { Route as ProtectedOrdersIndexRouteImport } from './routes/_protected/orders/index'
import { Route as ProtectedInventoryIndexRouteImport } from './routes/_protected/inventory/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCustomersIndexRouteImport } from './routes/_protected/customers/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedReportsIndexRoute = ProtectedReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInventoryIndexRoute = ProtectedInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCustomersIndexRoute = ProtectedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginIndexRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/inventory': typeof ProtectedInventoryIndexRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginIndexRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/inventory': typeof ProtectedInventoryIndexRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_protected/customers/': typeof ProtectedCustomersIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/inventory/': typeof ProtectedInventoryIndexRoute
  '/_protected/orders/': typeof ProtectedOrdersIndexRoute
  '/_protected/reports/': typeof ProtectedReportsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login/'
    | '/_protected/customers/'
    | '/_protected/dashboard/'
    | '/_protected/inventory/'
    | '/_protected/orders/'
    | '/_protected/reports/'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reports/': {
      id: '/_protected/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/orders/': {
      id: '/_protected/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/': {
      id: '/_protected/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ProtectedInventoryIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/customers/': {
      id: '/_protected/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedCustomersIndexRoute: typeof ProtectedCustomersIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedInventoryIndexRoute: typeof ProtectedInventoryIndexRoute
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute
  ProtectedReportsIndexRoute: typeof ProtectedReportsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCustomersIndexRoute: ProtectedCustomersIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedInventoryIndexRoute: ProtectedInventoryIndexRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedReportsIndexRoute: ProtectedReportsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
